# Generated by Django 3.2.9 on 2021-11-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_address.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_address.division'),
        ),
        migrations.AlterField(
            model_name='address',
            name='upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_address.upazila'),
        ),
    ]
