# Generated by Django 3.2.9 on 2021-11-26 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('cellphone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('nid', models.CharField(blank=True, default='', max_length=20)),
                ('birth_reg_no', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, default='', max_length=10)),
                ('nationality', models.CharField(blank=True, default='', max_length=20)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('maritial_status', models.CharField(blank=True, default='', max_length=20)),
                ('created_on', models.DateTimeField()),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('modified_on', models.DateTimeField()),
                ('modified_by', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_address.address')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
