# Generated by Django 4.0 on 2021-12-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('urea', models.CharField(blank=True, default='', max_length=100)),
                ('tsp', models.CharField(blank=True, default='', max_length=100)),
                ('mop', models.CharField(blank=True, default='', max_length=100)),
                ('gipsam', models.CharField(blank=True, default='', max_length=100)),
                ('zinc', models.CharField(blank=True, default='', max_length=100)),
                ('user', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
